# ==== WinterWeather Configuration ====
# You can safely keep old configs; missing fields get added automatically
# If this version is lower than the plugin's version, migrations will run.
config-version: 1

frost:
  criticalFreezingTicks: 1800
  playerRadius: 5.0
  interpolationFunction: 'smootherstep'
  debug: true

  isolation:
    maxPossibleIsolation: 80

    armourPieces:
      LEATHER_BOOTS: 15
      LEATHER_LEGGINGS: 30
      LEATHER_CHESTPLATE: 40
      LEATHER_HELMET: 15

  playerBurningBoost: 10
  playerPowderSnowBoost: 0

  heatSources:
    TORCH:
      value: 1.0
      radius: 3.0
    CAMPFIRE:
      value: 2.0
      radius: 3.0
    FIRE:
      value: 3.0
      radius: 5.0
    LAVA:
      value: 3.0
      radius: 7.0
    LANTERN:
      value: 1.0
      radius: 3.0